[WIP] Website fix
hack4impact/uiuc.hack4impact.org pull request #122
Opened 2019-05-17 22:48 UTC by choiboy98

resolves #121

2019-05-18 18:09 UTC, rgychiu requested changes

2019-05-18 18:09 UTC, rgychiu commented on components/homepage/ourWork.js
> +    subtitle="How might we create a single portal where users can easily track their progress and upload documents?"
This is too simple and vague description for Kiva. Yes, what we did was create a portal where users can easily track their progress and upload documents, but the overarching problem is much bigger than this. Kiva crowdfunds and distributes many loans worldwide and relies on a network of Field Partners through which they can vet nonprofits, disburse loans, etc. In order to constantly have such a large network, the portfolio managers need to collect financial documents from these Field partners. So yes, what we did was create a single portal where users can easily track their progress and upload documents, but the overarching problem is how do we expedite/simplify the reporting process for loan partners/field partners.

2019-05-18 18:09 UTC, rgychiu commented on data/projects/semesters/sp19/kiva-2.js
> +      "Required documents are organized by their status, and portfolio managers can reject or approve them to indicate based on their completions.",
indicate based on their completions sounds a little off to me

2019-05-18 18:09 UTC, rgychiu commented on data/projects/semesters/sp19/gg-2.js
> -    }
What's the reason for deleting Bag of Words and Word Vectors - is it because there's too many tabs on the project page?

2019-05-21 06:16 UTC, tko22 commented
could you post screenshots, I don't want to run the website (screenshot the entire browser window)

2019-05-22 05:13 UTC, choiboy98 commented on data/projects/semesters/sp19/gg-2.js
> -    }
There were too many tabs, but also there's already a document vector, so I thought word vector was not too necessary. The reason why I deleted Bag of Words is because I do not think it provides as much information as the other tabs.

2019-05-22 05:17 UTC, choiboy98 commented
![Uploading Screen Shot 2019-05-21 at 10.14.43 PM.png…](Main page with listed projects)
![Uploading Screen Shot 2019-05-21 at 10.14.49 PM.png…](Other chapters)
![Uploading Screen Shot 2019-05-21 at 10.14.55 PM.png…](Project tab)
![Uploading Screen Shot 2019-05-21 at 10.15.01 PM.png…](Kiva)
![Uploading Screen Shot 2019-05-21 at 10.15.13 PM.png…](SafeMaps previous project button)
![Uploading Screen Shot 2019-05-21 at 10.15.17 PM.png…](SafeMaps)
![Uploading Screen Shot 2019-05-21 at 10.15.27 PM.png…](Global Giving)

2019-05-25 09:05 UTC, tko22 commented
- Can we make the Chapter Logos 25-40% smaller? And maybe add a little bit more spacing between the "Other Chapters" Title and the logos? 
- Cornell and BU's logos are very similar, maybe separate them with another school instead?
- Georgia Tech and Upenn logos look like they are stretched vertically. I would adjust their height. Tip: look at the original dimensions of the logo and adjust the height accordingly based on the width (if the proportional height is greater than the other logos, make the width smaller and adjust accordingly)

Otherwise, the rest looks great!

2019-05-25 09:06 UTC, tko22 commented on components/homepage/clientSlider.js
> +    link: "/projects?name=kiva-2"
you could add another kiva logo and link it to `kiva-1` - just place the kiva logos like 2-3 logos away from each other

2019-05-25 09:07 UTC, tko22 commented on components/homepage/otherChapters.js
> +            <BackgroundSlider duration={40}>
good job figuring this out!

2019-05-25 09:08 UTC, tko22 commented on components/projects/specificProjectPage.js
> +          previousLink={project.previousLink}
I like this addition!

2019-05-25 09:22 UTC, tko22 commented
would love it if you could set up a Zeit Now Auto deployment for just Pull Requests. Essentially, whenever someone makes a PR and makes new commits to it, it would deploy the app based on the branch and post the link in the PR. Then, there would be no need for screenshots! https://zeit.co/docs/v2/integrations/now-for-github/ I've added you to our zeit account, but make sure to not deploy master... because we use surge.sh for that because of domain name stuff with national

check out `circle.yml` for deployment commands. We generate static files with next.js with npm/yarn and then deploy those static files

2019-06-12 02:58 UTC, merged

2019-06-12 06:03 UTC, tko22 commented
@choiboy98  remember to remove the `[WIP]` bracket from your commit and PR next time you merge :)